spring:
  data:
    mongodb:
#      username: root
#      password: 123456
#      database: communication_circle_album
#mongodb://name:pass@localhost:27017/test
      uri: mongodb://communication:123456@localhost:27017/communication_circle_album
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:password123@localhost:8010/eureka/

swagger:
  enabled: true
  title: 朋友圈相册服务提供
  base-package: com.own.microservice.provide.rfriends.circle.album.controller
