spring:
  data:
    mongodb:
      #username: communication
      #password: 123456
      database: communication_circle_comment
      uri: mongodb://39.104.16.81:27017
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

logging:
  level:
    com.own.microservice.provide.rfriends.circle.album: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:password123@localhost:8010/eureka/

swagger:
  enabled: true
  title: 朋友圈评论服务提供者
  base-package: com.own.microservice.provider.friends.circle.comment.controller